[package]
name = "code"
version = "0.1.0"
authors = ["Jeffrey Xiao <jeffrey.xiao1998@gmail.com>"]

[dependencies]
kademlia = { path = "kademlia" }
hash = { path = "hash" }
data_structures = { path = "data_structures" }
clippy = { version = "*", optional = true }

[workspace]
