[package]
name = "code"
version = "0.1.0"
authors = ["Jeffrey Xiao <jeffrey.xiao1998@gmail.com>"]

[dependencies]
rand = "0.4"
kademlia = { path = "kademlia" }
clippy = { version = "*", optional = true }

[profile.bench]
debug = true
