[package]
name = "kademlia"
version = "0.1.0"
authors = ["Jeffrey Xiao <jeffrey.xiao1998@gmail.com>"]

[dependencies]
clippy = { version = "*", optional = true }
rand = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
time = "0.1"

[dev-dependencies]
num-bigint = "0.1"
